name: Build NPM Package

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish Package to NPM'
        type: boolean
        default: false

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # do initial pull of source w/o submodules to save time if npm install or beachball:check fails
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4.0.1

    - name: Pull NPM Packages
      run: npm install

    - name: Check for changefiles
      if: ${{ !inputs.release }}
      run: npm run beachball:check

    - name: Create changelog & bump version
      if: ${{ inputs.release }}
      # For testing without actually bumping use the below run instead...
      # run: npm run beachball:bump -- --no-commit --no-push
      run: npm run beachball:bump -- --no-commit --no-push

    - name: Run build & Pack
      run: npm run pack

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          dist/**
          CHANGELOG.md
