name: CI Build

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # do initial pull of source w/o submodules to save time if npm install or beachball:check fails
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4.0.1

    - name: Run npm ci Command
      run: npm ci

    - name: Check for changefiles
      run: npm run beachball:check

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          dist/**
          CHANGELOG.md
