name: Release NPM Package

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

    # do initial pull of source w/o submodules to save time if npm install or beachball:check fails
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4.0.1
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: FAIL -- NOTE that releasing via Actions is currently disabled
      run: exit 1
      
    - name: Run npm ci Command
      run: npm ci

    - name: Run ESlint
      run: npm run eslint

    - name: Run build
      run: npm run build:only

    - name: Run prettier
      run: npm run format-check

    - name: Run unit tests
      run: npm run test

    - name: Create changelog & bump version
      run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          npm run beachball:publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          dist/**
          CHANGELOG.md
